<a href="https://colab.research.google.com/github/Roshanshres/numpy/blob/main/14_Numpy_Advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
# Numpy vs Array List
#numpy is 50 timesfaster than python list/
#


In [2]:
#Advance Indexing
a = np.array(12).reshape(4,3)
a

ValueError: ignored

In [ ]:
#fancy indexing ??


In [3]:
#boolean indexing
import numpy as np

a = np.random.randint(1,100,24).reshape(6,4)

a

array([[82, 90, 58, 10],
       [17, 38, 91, 49],
       [29, 42, 28, 42],
       [ 8, 76, 58,  7],
       [55, 13,  6, 99],
       [81, 60, 51, 72]])

In [ ]:
#greater tha 50
a>50

array([[False, False,  True, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False,  True,  True, False]])

In [ ]:
#boolean mask
#arko ma number halni
a[a>50]

array([79, 69, 90, 64, 64, 81, 82])

In [ ]:
#even number
a%2 ==0

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False,  True, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [False, False,  True,  True]])

In [ ]:
a[a > 50]

array([79, 69, 90, 64, 64, 81, 82])

In [ ]:
#greater than 50 and even number
(a>50) & (a%2 == 0)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False,  True, False]])

In [ ]:
#not divisible by 7
a[a%7 == 0]

array([49, 21])

**Broadcasting**
The term broadcasting describes how Numpy treats array with different shapes, during arithematic operations. The smaller array is "broadcast" across the larger arrary so that have compatible.

In [4]:
#same shape
a = np.arange(6).reshape(2,3)
b = np.arange(6, 12).reshape(2,3)

print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [5]:
a = np.arange(6).reshape(2,3)
b = np.arange(6, 12).reshape(2,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]


In [7]:
#different shapes
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]


In [8]:
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]
