<a href="https://colab.research.google.com/github/Roshanshres/numpy/blob/main/14_Numpy_Advanced.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# Numpy vs Array List
#numpy is 50 timesfaster than python list



In [4]:
#Advance Indexing
a = np.array(12).reshape(4,3)


a

ValueError: ignored

In [ ]:
#fancy indecxing


In [5]:
#boolean indexing
import numpy as np

a = np.random.randint(1,100,24).reshape(6,4)

a

array([[23,  3, 79, 23],
       [38, 49,  9, 69],
       [11,  3, 90, 45],
       [36, 18, 64, 32],
       [18, 21, 44, 64],
       [43, 81, 82, 44]])

In [6]:
#greater tha 50
a>50

array([[False, False,  True, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False,  True,  True, False]])

In [7]:
#boolean mask
#arko ma number halni
a[a>50]

array([79, 69, 90, 64, 64, 81, 82])

In [8]:
#even number
a%2 ==0

array([[False, False, False, False],
       [ True, False, False, False],
       [False, False,  True, False],
       [ True,  True,  True,  True],
       [ True, False,  True,  True],
       [False, False,  True,  True]])

In [9]:
a[a > 50]

array([79, 69, 90, 64, 64, 81, 82])

In [10]:
#greater than 50 and even number
(a>50) & (a%2 == 0)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True, False],
       [False, False,  True, False],
       [False, False, False,  True],
       [False, False,  True, False]])