<a href="https://colab.research.google.com/github/Roshanshres/numpy/blob/main/numpy_fundametals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# fixed size arrray in numpy
# is homogeneous data type


In [2]:
#creating NumPy Arrays
#np.array
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
#1D vector array
a = np.array ([1,2,3])
# print(type(a))
print(a)

[1 2 3]


In [ ]:
#2D and 3D
#2D = Maxtrix
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D
#tensor
c = np.array([[[1,2], [3,4],[5,6],[6,7],[7,8]]])
print(c)


[[[1 2]
  [3 4]
  [5 6]
  [6 7]
  [7 8]]]


In [ ]:
#datatype as own wise
# float dt array

# np.array([1,2,3], dtype = float)
#np.array([1,2,3], dtype = int)
# np.array([1,2,3], dtype = bool)
np.array([1,2,3], dtype = complex)




array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#with reshape
np.arange(1,11).reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#np ones and np zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np random ---> to initialize
np.random.random((3,4))

array([[0.07369169, 0.5285386 , 0.614683  , 0.60644478],
       [0.41774455, 0.27601823, 0.79920309, 0.18287302],
       [0.16057113, 0.13314742, 0.87844825, 0.54341417]])

In [ ]:
np.linespace(-10,10,10)

AttributeError: ignored

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Arrays attributes
a1 = np.arange(10) #--vector
a2 = np.arange(12, dtype = float).reshape(3,4) #matrix
a3 = np.arange(8).reshape(2,2,2) #vector

In [ ]:
#ndim-- no.of dimenrsions
a3.ndim

3

In [ ]:
#shape
print(a3.shape)
a2

(2, 2, 2)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
#itemsize
a1.itemsize

8

In [ ]:
#changing inn datatypes
#astype
a3.dtype


dtype('int64')

In [ ]:
a3.astype(np.int32) # convet

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [3]:
#Array Operations i.e all mathematical operations
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
#two types of operation
#scalar operation and vector operarions
#1 Scalar Operations

a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [12]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [14]:
# relational operators
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [15]:
#2 Vector <operations
a1 +a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [17]:
#Array Functions
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

a1

array([[64., 17., 35.],
       [11., 49., 31.],
       [95., 60., 49.]])

In [18]:
np.max(a1)

95.0

In [19]:
np.min(a1)

11.0

In [20]:
np.sum(a1)

411.0

In [4]:
# 0= col
# 1= row
np.max(a1, axis= 1)

array([ 3,  7, 11])

In [5]:
np.max(a1, axis = 0)

array([ 8,  9, 10, 11])

In [6]:
#statstic
#mean/ median/standard deviation/ var
np.mean(a1)

5.5

In [7]:
np.mean(a1, axis = 0)

array([4., 5., 6., 7.])

In [9]:
np.mean(a2, axis = 1)

array([13.5, 17.5, 21.5])

In [10]:
np.median(a1, axis=1)

array([1.5, 5.5, 9.5])

In [11]:
np.std(a1, axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [12]:
np.var(a1)

11.916666666666666

In [16]:
#dot-product
# eg 2 metrix ko product same if (2,3) shoud (3,2)

a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)


In [17]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [21]:
#log and exponents
a1
np.log(a1)

<ipython-input-21-87743887e068>:3: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [22]:
np.exp(a1)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [24]:
#round/floor/ceil
np.random.random((2,3))

array([[0.45496645, 0.94027857, 0.34209856],
       [0.50853108, 0.58791946, 0.03598865]])

In [25]:
np.random.random((2,3))*100

array([[13.34954562, 52.59754144, 69.08988784],
       [76.96659975, 36.24799537, 35.11980535]])

In [27]:
#for integer we use round
np.round(np.random.random((2,3))*100)

array([[72., 74., 10.],
       [86., 19., 24.]])

In [28]:
np.floor(np.random.random((2,4))*100)

array([[65., 78., 99.,  0.],
       [90., 54., 19., 85.]])

In [29]:
np.ceil(np.random.random((2,3))*100)

array([[ 48.,  40., 100.],
       [ 43.,  70.,  40.]])

In [9]:
#Indexing and slicing
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
#Indexing
# a1[0]
a1[1]

1

In [13]:
# 2D
a2[1,3]

7

In [14]:
# 3D
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [17]:
a3[0,0,1]

1

In [19]:
a3[1,1,0]

6