<a href="https://colab.research.google.com/github/Roshanshres/numpy/blob/main/numpy_fundametals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# fixed size arrray in numpy
# is homogeneous data type


In [9]:
#creating NumPy Arrays
#np.array
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [ ]:
#1D vector array
a = np.array ([1,2,3])
# print(type(a))
print(a)

[1 2 3]


In [ ]:
#2D and 3D
#2D = Maxtrix
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D
#tensor
c = np.array([[[1,2], [3,4],[5,6],[6,7],[7,8]]])
print(c)


[[[1 2]
  [3 4]
  [5 6]
  [6 7]
  [7 8]]]


In [ ]:
#datatype as own wise
# float dt array

# np.array([1,2,3], dtype = float)
#np.array([1,2,3], dtype = int)
# np.array([1,2,3], dtype = bool)
np.array([1,2,3], dtype = complex)




array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
#with reshape
np.arange(1,11).reshape(2,5)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#np ones and np zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np random ---> to initialize
np.random.random((3,4))

array([[0.07369169, 0.5285386 , 0.614683  , 0.60644478],
       [0.41774455, 0.27601823, 0.79920309, 0.18287302],
       [0.16057113, 0.13314742, 0.87844825, 0.54341417]])

In [ ]:
np.linespace(-10,10,10)

AttributeError: ignored

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Arrays attributes
a1 = np.arange(10) #--vector
a2 = np.arange(12, dtype = float).reshape(3,4) #matrix
a3 = np.arange(8).reshape(2,2,2) #vector

In [ ]:
#ndim-- no.of dimenrsions
a3.ndim

3

In [ ]:
#shape
print(a3.shape)
a2

(2, 2, 2)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
#size
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
#itemsize
a1.itemsize

8

In [ ]:
#changing inn datatypes
#astype
a3.dtype


dtype('int64')

In [ ]:
a3.astype(np.int32) # convet

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [10]:
#Array Operations i.e all mathematical operations
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
#two types of operation
#scalar operation and vector operarions
#1 Scalar Operations

a1 * a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [12]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [14]:
# relational operators
a2 > 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [15]:
#2 Vector <operations
a1 +a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [17]:
#Array Functions
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

a1

array([[64., 17., 35.],
       [11., 49., 31.],
       [95., 60., 49.]])

In [18]:
np.max(a1)

95.0

In [19]:
np.min(a1)

11.0

In [20]:
np.sum(a1)

411.0